-- 1. Crear tipos ENUM
CREATE TYPE estado_tarea AS ENUM ('pendiente', 'en_progreso', 'completada');
CREATE TYPE prioridad_tarea AS ENUM ('baja', 'media', 'alta');

--2. Tabla de Usuarios
CREATE TABLE usuarios (
    id SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50),
    FECHA_NACIMIENTO DATE,
    CORREO VARCHAR(100) NOT NULL UNIQUE,
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM usuarios

--3. Tabla de Tareas
CREATE TABLE TAREAS (
    ID SERIAL PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    ESTADO estado_tarea DEFAULT 'pendiente',
    PRIORIDAD prioridad_tarea DEFAULT 'media',
    USUARIO_ID INT REFERENCES usuarios(ID) ON DELETE CASCADE,
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Tabla de Categorías
CREATE TABLE CATEGORIAS (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE
);

-- 5. Tabla de relación muchos a muchos
CREATE TABLE TAREAS_CATEGORIAS (
    TAREA_ID INTEGER REFERENCES TAREAS(ID) ON DELETE CASCADE,
    CATEGORIA_ID INTEGER REFERENCES CATEGORIAS(ID) ON DELETE CASCADE,
    PRIMARY KEY (TAREA_ID, CATEGORIA_ID)
);

